### ISSUE TITLE
Epic : Calendar Rendering and Navigation 

### ISSUE THREAD

**Issue by Jahnavi-0305** [Jahnavi-0305/Project-3#5]
Title: Implement Calendar Rendering and Navigation 
As a developer, I want the assignee to ensure that the DatePicker class can correctly render a one-month calendar within an HTML element.

**Comment by ruchitha007** [comment]
-   Acceptance Criteria:   
  - The DatePicker class should display a one-month calendar within the specified HTML element. 
  - The calendar should include a grid format with days of the selected month. 
  - Navigation controls should be provided to allow users to switch to the previous or next month. 
  - Days from other months should be displayed in a dimmed fashion to indicate they are not part of the current month. 
  - Users should be able to click on valid days to select them, triggering the callback function

function render(date) {
        const container = document.getElementById(id);
        if (!container) {
            console.error(`Element with id "${id}" not found.`);
            return;
        }

        // Create a new date object to avoid modifying the original date
        const selectedDate = new Date(date);

        // Calculate the first day of the month
        selectedDate.setDate(1);

        // Create the calendar HTML
        let calendarHTML = `
      <div class="header">
        <span class="prev-month">&lt;</span>
        <span class="current-month">${selectedDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</span>
        <span class="next-month">&gt;</span>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th class="day-header">Su</th>
            <th class="day-header">Mo</th>
            <th class="day-header">Tu</th>
            <th class="day-header">We</th>
            <th class="day-header">Th</th>
            <th class="day-header">Fr</th>
            <th class="day-header">Sa</th>
          </tr>
        </thead>
        <tbody>
    `;


        const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

        const currentDate = new Date();
        const currentYear = currentDate.getFullYear();
        const currentMonth = currentDate.getMonth();
        const currentDay = currentDate.getDate();
        // Calculate the number of days in the month
        let daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();

        // Calculate the day of the week for the first day of the month (0 = Sunday, 6 = Saturday)
        const firstDayOfWeek = selectedDate.getDay();

        // Calculate the number of days to display from the previous month
        const daysFromPrevMonth = (firstDayOfWeek === 0 ? 6 : firstDayOfWeek - 1);

        // Calculate the date of the first day to display
        const firstDate = new Date(selectedDate.getFullYear(), selectedDate.getMonth(), 1);
        firstDate.setDate(1 - daysFromPrevMonth);

        // Fill in the calendar with days
        for (let week = 0; week < 6; week++) {
            calendarHTML += '<tr>';
            for (let day = 0; day < 7; day++) {
                const currentDay = new Date(firstDate);
                currentDay.setDate(currentDay.getDate() + (week * 7) + day);
                const isCurrentMonth = currentDay.getMonth() === selectedDate.getMonth();

                if (!isCurrentMonth) {
                    // Display days from the previous or next month
                    calendarHTML += `<td class="disabled">${currentDay.getDate()}</td>`;
                } else {
                    // Display clickable days for the current month
                    const dateObject = {
                        month: currentDay.getMonth() + 1,
                        day: currentDay.getDate(),
                        year: currentDay.getFullYear(),
                    };
                    calendarHTML += `<td class="clickable" onclick="selectDate(${JSON.stringify(dateObject)})">${currentDay.getDate()}</td>`;
                }
            }
            calendarHTML += '</tr>';
        }

        calendarHTML += `
        </tbody>
      </table>
    `;

        container.innerHTML = calendarHTML;

        // Add event listeners to the arrow spans
        const prevMonthSpan = container.querySelector('.prev-month');
        const nextMonthSpan = container.querySelector('.next-month');
        prevMonthSpan.addEventListener('click', () => prevMonth());
        nextMonthSpan.addEventListener('click', () => nextMonth());
    }

**Comment by ruchitha007** [comment]
Test Scenario 1: Navigation Controls   
  -   Test Case 1:   Click the "Previous Month" control. 
	-   Expected Result:   The calendar should switch to display the previous month accurately. 
  -   Test Case 2:   Click the "Next Month" control. 
	-   Expected Result:   The calendar should switch to display the next month accurately. 
 
-   Test Scenario 2: Display of Days from Other Months   
  -   Test Case 1:   Verify that days from previous and next months are displayed in a dimmed fashion. 
	-   Expected Result:   Days from other months should be visually distinguishable but still visible.

**Comment by Sharu201101** [comment]
- Error handling is robust and provides clear feedback for invalid inputs. 
	- Code readability is decent, but there is room for improvement in variable naming and code organisation. 
	- Adequate comments are present, but some functions could benefit from additional comments explaining their purpose.

**Comment by ruchitha007** [comment]
review the above code - 
  Review Criteria:   
	- Check that the calendar is correctly rendered in a grid format with accurate day placement. 
	- Verify the functionality of the navigation controls, ensuring they switch between months as expected. 
	- - Evaluate the display of days from other months to confirm that they are appropriately dimmed. 
	- Test the date selection mechanism to ensure that valid days can be selected and that the callback function triggers 
	correctly.

**Comment by Sharu201101** [comment]
-   Comments:   
	- The calendar rendering appears to be accurate, with days organised in a grid as required. 
	- The navigation controls function as expected, allowing smooth transitions between months. 
- Days from other months are displayed as dimmed, meeting the visual requirements. 
	- The date selection mechanism works as intended, allowing users to select valid days and triggering the callback function correctly. 
  - The DatePicker class successfully renders the calendar, provides navigation controls, displays days from other months appropriately, and allows users to select valid dates. Testing results indicate that the implementation meets the specified requirements.
