### ISSUE TITLE
epic: Create CSS Styles for Date Pickers

### ISSUE THREAD

**Issue by Sharu201101** [Jahnavi-0305/Project-3#6]
As a developer, I want the assignee to create a CSS stylesheet named "datepicker.css" to apply styling to the date pickers generated by the DatePicker class.

**Comment by Jahnavi-0305** [comment]
/* Add your styles here */
.header {
    width:30%;
    text-align: center;
    padding: 10px 0;
    background-color: #944444;
    color: #fff;
}

.header span {
    cursor: pointer;
    margin: 0 5px;
    font-size: 15px;
    border: 2px solid #944444;
    border-radius: 5px;
}

.current-month {
    width:50%;
    font-size: 20px;
    border: 2px solid #944444;
    border-radius: 5px;
}

.table {
    width: 30%;
    border-collapse: separate;
}

.table th,
.table td {
    padding: 12px;
    text-align: center;
    border: 2px solid #ccc;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.table th {
    font-weight: bold;
    color: #333;
    background-color: #f2f2f2;
}

.table td {
    background-color: #fff; /* White background for table cells */
}


.table td.clickable {
    cursor: pointer;
    background-color: #e0e0e0;
}

.table td.disabled {
    background-color: #f5f5f5;
    color: #ccc;
}

.table td.clickable:hover {
    background-color: #e2ed00;
    color: #944444;
}

Acceptance Criteria:   
  - A CSS stylesheet named "datepicker.css" should be created. 
  - The CSS styles should be applied to enhance the visual appearance and user-friendliness of the date pickers. 
  - Styling should include elements such as the calendar grid, header, navigation controls, and day highlighting. 
  - The applied styles should provide a pleasant and intuitive user experience.

**Comment by Jahnavi-0305** [comment]
Kindly test the given code.

Issue Testing:   
Test Scenario 1: Styles Applied to Calendar Grid   
-   Test Case 1:   Verify that the calendar grid is styled appropriately. 
-   Expected Result:   The calendar grid should have visually appealing styling that makes it easy to distinguish between days. 
 
Test Scenario 2: Styles Applied to Header   
-   Test Case 1:   Confirm that the calendar header is styled as intended. 
-   Expected Result:   The header should be visually appealing and provide clear information about the displayed month and year. 
 
Test Scenario 3: Styles Applied to Navigation Controls   
-  Test Case 1:   Check that the navigation controls (e.g., "<" and ">") are styled appropriately. 
-   Expected Result:   The navigation controls should be visually distinctive and easy to interact with.

**Comment by ruchitha007** [comment]
Testing review-
- All test scenarios and test cases have been executed and passed without issues. 
- No unexpected behaviours or edge cases were encountered during testing.

**Comment by ruchitha007** [comment]
please review the above code
 Review Criteria1:   
	- Check the "datepicker.css" stylesheet to ensure that styles are applied consistently and appropriately. 
	- Evaluate the styling of the calendar grid, header, navigation controls, and day highlighting. 
 Review Criteria2:   
	- Test the date pickers in conjunction with the "datepicker.css" stylesheet to ensure that styling enhances the user 
	experience. 
Review Criteria3:   
	- Execute the user stories and test cases related to the visual appearance and styling of the date pickers. 
	- Check for any issues or inconsistencies in the styling.

**Comment by Sharu201101** [comment]
- The "datepicker.css" stylesheet appears to apply styles consistently and appropriately. 
	- Calendar grid, header, and navigation controls are styled in a visually appealing manner. 
	- The day highlighting for selected dates is distinct and clear. 
- The styles applied by "datepicker.css" enhance the user experience and provide a visually pleasing interface. 
	- Calendar elements, including the grid, header, navigation controls, and day highlighting, are styled in a user-friendly manner. 
 All test scenarios related to styling have been executed and passed successfully. 
	- The "datepicker.css" stylesheet provides a cohesive and user-friendly design, and no styling issues were identified. 
 
-   Review Summary:   
  - The "datepicker.css" stylesheet successfully applies styles to the date pickers, enhancing their visual appeal and user-friendliness. Testing results confirm that the styling meets the defined requirements, creating a pleasant user experience.
