### ISSUE TITLE
Epic : Accurate Template Processing and Replacement

### ISSUE THREAD

**Issue by KpSai96** [Jahnavi-0305/Project-3#9]
Title: Implement Accurate Template Processing and Replacement
-The TableTemplate class should accurately process templates within HTML tables. This includes identifying and replacing template strings in both the header row and specified columns. 
-The class should also gracefully handle cases where template properties are missing in the dictionary, replacing them with empty strings.

**Comment by BhavagnaT** [comment]
'use strict';

class TemplateProcessor {
    constructor(template) {
        this.template = template;
    }
    fillIn(dictionary) {
        let returnString = this.template;
        for (const property in dictionary) {
            if (Object.prototype.hasOwnProperty.call(dictionary, property)) {
                const regex = new RegExp("{{" + property + "}}", "g");
                returnString = returnString.replace(regex, dictionary[property]);
            }
        }
        const regex = /{{.*?}}/g; // Updated regex to match non-greedy
        returnString = returnString.replace(regex, "");
        return returnString;
    }
}

// Example usage:
const template = "Hello, {{name}}! Today is {{day}}.";
const dictionary = { name: "Alice", day: "Monday" };
const processor = new TemplateProcessor(template);
const result = processor.fillIn(dictionary);
console.log(result);

Acceptance Criteria:
The class should correctly identify and replace template strings within the header row of the table.
The class should accurately replace template strings within the specified columns.
Template processing should not affect non-template content in the table.

**Comment by BhavagnaT** [comment]
please test the following test scenarios:

Issue Testing:
Test Scenario 1: Header Template Processing
Test Case 1: Create a table with a header row containing valid template strings (e.g., "{{property}}").
Expected Result: The TableTemplate class should replace the template strings in the header row with the corresponding values from the dictionary.
Test Case 2: Create a table with a header row containing no template strings.
Expected Result: The TableTemplate class should not modify the header row when no template strings are present.
Test Scenario 2: Column Template Processing
Test Case 1: Create a table with a specified column containing valid template strings.
Expected Result: The TableTemplate class should replace the template strings in the specified column with the corresponding values from the dictionary.
Test Case 2: Create a table with a specified column containing no template strings.
Expected Result: The TableTemplate class should not modify the specified column when no template strings are present.

**Comment by suhasss077** [comment]
- All test scenarios and test cases have been executed and passed without issues. 
	- No unexpected behaviours or edge cases were encountered during testing.

**Comment by suhasss077** [comment]
Review Criteria:

- Check if the TableTemplate class correctly identifies and replaces template strings within the header row.
- Verify that template strings within specified columns are accurately replaced.
- Ensure that the class doesn't interfere with non-template content.
- Evaluate the code for potential issues related to template processing and replacement.
- Check for any cases where template strings are not replaced accurately.
- Ensure that the code adheres to coding standards and practices.
- Execute test cases outlined in the "Issue Testing" section to validate that template processing and replacement function correctly.
- Check for any unexpected issues or errors.

**Comment by KpSai96** [comment]
- The constructor initialisation appears to be implemented correctly, handling both valid and invalid inputs.
- The template processing logic functions as expected, replacing templates accurately.
- Error handling for invalid inputs is robust and provides clear feedback.
- The code adheres to coding standards and is reasonably readable.
- Comments are present, but some functions could benefit from additional explanations.
- All defined test scenarios and test cases have been executed and passed successfully.
- No unexpected behaviours or edge cases were encountered during testing.

Review Summary:
The TableTemplate class implementation generally meets the defined requirements and passes testing. Some areas for improvement include code readability and additional comments for clarity. Error handling and template processing are commendable, ensuring robust functionality.
